### ISSUE TITLE
Remote data with ajax.. how to do it?

### ISSUE THREAD

**Issue by giacomorebonato** [nate-strauser/meteor-select2#10]
I am looking for an example for feeding Select2 with remote data.
I know how to use an ajax request with other standard web framework, but how should I write it to use with a Meteor server method?

**Comment by giacomorebonato** [comment]
I didn't know I could use Iron Router to write REST API too. Here is an example that I used successfully with Select2.

    Router.route('/geo/get_location', {
    	where: 'server'
    }).get(function() {
    	var url = 'https://maps.googleapis.com/maps/api/place/autocomplete/json?';
    	url += 'input=' + this.params.query.input + '&types=(cities)&key=' + consts.google_api_key;
    
    
    	var res = HTTP.get(url)
    	this.response.setHeader('Content-Type', 'application/json');
    
    	var mapped = res.data.predictions.map(function(obj) {
    		return {
    			id: obj.id,
    			text: obj.description
    		}
    	})
    
    	this.response.end(JSON.stringify(mapped))
    })

**Comment by thearabbit** [comment]
I try too, but get error 
```js
GET http://localhost:3000/sample/customerAddress 500 (Internal Server Error)
```

**Comment by thearabbit** [comment]
my code
```js
// client
$('[name="addressId"]').select2({
        ajax: {
            url: 'sample/remoteAddress',
            type: 'GET',
            dataType: 'json',
            delay: 250,
            data: function (params) {
                var query = {
                    term: params
                };

                return query;
            },
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
        },
        minimumInputLength: 1
    });

// Common
Router.route('sample/remoteAddress', {
    name: 'sample.remoteAddress',
    where: 'server'
}).get(function () {
    var q = this.params.query;

    console.log(q.term);

    var mapped = [
        {id: 'A', text: 'A'},
 {id: 'A', text: 'A'}
    ];
    this.response.setHeader('Content-Type', 'application/json');

    this.response.end(JSON.stringify(mapped))
});
```
