### ISSUE TITLE
Error when dismissing modal with select2

### ISSUE THREAD

**Issue by elewis33** [nate-strauser/meteor-select2#25]
Getting this error in the console when dismissing/closing a modal that has select2 in an AutoForm.

```
The select2('destroy') method was called on an element that is not using Select2.
```

Seems odd, since there is clearly a select2 in the modal/autoform.

**Comment by onedr0p** [comment]
+1

**Comment by nate-strauser** [comment]
i'm thinking this is not an problem with this repo - maybe belongs here https://github.com/aldeed/meteor-autoform-select2/issues

--

if you disagree, please provide an example of exactly how you are using this package with autoform, angular, and the modal

**Comment by elewis33** [comment]
You're probably right. I was just posting it here because it bubbled up via your package. 

![Image of error] (http://i65.tinypic.com/1zfsle0.jpg)

I understand that there are some is a dependency between your select2 package that the aldeed:autoform-select2, but I'm not intimate with the details, so thought I'd start here.

**Comment by elewis33** [comment]
Oh, and just FYI, I'm using a straight Blaze implementation here, no Angular, if that matters.

**Comment by nate-strauser** [comment]
odd - the current version of autoform-select2 does not have any link to this package - see https://github.com/aldeed/meteor-autoform-select2 - the readme indicates you should cdn load select2
