### ISSUE TITLE
Meteor 1.3 support

### ISSUE THREAD

**Issue by neil-s** [nate-strauser/meteor-select2#30]
Has anyone had any luck using this package with Meteor 1.3?

I just updated my application, and the select2s (generated by autoforms within yogiben:meteor-admin) are just rendering as normal HTML selection lists. I haven't isolated the problem yet but of course this package must be part of the issue.

**Comment by nate-strauser** [comment]
are you actually including this package directly?  pretty sure that autoform and yogiben's admin do not use this package.

**Comment by neil-s** [comment]
I am. Thanks for such a quick response!

My full use case:

I needed to load some custom items in my select2, so I've copied the HTML + JS from aldeed:autoform-select2, and customized those to my needs. This code resides in `approot/client/` (I haven't yet switched away to the lazy-loading structure recommended in 1.3). Along with this application code, I use the following top-level packages and versions:

yogiben:admin@1.2.4
aldeed:autoform@5.8.1
natestrauser:select2@4.0.1
zimme:select2-bootstrap3-css@0.1.1

(note: I haven't selected any versions manually, these are copied out of the versions file created by meteor's own package management)

Since I don't directly control the template used on the admin pages, I'm using your package to load the select2 JS and CSS in at the right time (after jQuery, before the select widgets are rendered and the select2 initialisation function called). It works fine in Meteor 1.2, but breaks on update.

**Comment by nate-strauser** [comment]
this package is working just fine for me with a meteor 1.3 app

i'm using
aldeed:autoform
aldeed:autoform-select2
natestrauser:select2

the select2 plugin seems to work properly in my custom written admin interface

i think your issue may be something specific to your use case or the yogiben admin

**Comment by neil-s** [comment]
Sorry, isolated the bug, and it was with my application code, not this package. Specifically, I was using `Template.<templatename>.rendered = function () {...}` to initialize the plugin, rather than the documented `Template.<templatename>.onRendered(function () {...})`. Changing to the latter fixed my issue.
