### ISSUE TITLE
problem with selected value when onchange any btn?

### ISSUE THREAD

**Issue by thearabbit** [nate-strauser/meteor-select2#8]
I try use event `click` of any `btn`, then change selected value of select2 object.
but don't work.
```js
$('[name="address"]').select2({
                val: 'PP'
            });
```
pl help me.

**Comment by dkmooers** [comment]
I think what you want is

$('[name="address"]').select2("val", "PP");

**Comment by thearabbit** [comment]
Thanks, but don't work.
If I set `setTimeout` with 100 ms, it is work.
I don't understand.

**Comment by thearabbit** [comment]
Maybe problem with `pub/sub`.
