### ISSUE TITLE
Upgrade select2 lib to 4.0

### ISSUE THREAD

**Issue by abhishekbatra** [nate-strauser/meteor-select2#9]
Hi,

Select2 has released a [4.0.0-rc.1](https://github.com/select2/select2/releases/tag/4.0.0-rc.1). FYI I created a [fork](https://github.com/abhishekbatra/meteor-select2) which uses this release. Are we waiting for a full release, or can it be upgraded now?

Thanks,
Abhishek

**Comment by nate-strauser** [comment]
i'll publish an upgrade when the new release is offically out

**Comment by yuomtheara** [comment]
+1

**Comment by ricardodovalle** [comment]
:+1:

**Comment by almogdesign** [comment]
I would also like this, I think there at a stable release any chance we can get an update?

**Comment by petermikitsh** [comment]
Select2 4.0 is out -> https://github.com/select2/select2/releases/tag/4.0.0

**Comment by thearabbit** [comment]
Now `Select2 4.0`  is out!!!!!!!!!!!

**Comment by abhishekbatra** [comment]
I'll try to prepare the package on the fork separately. Stay tuned.

**Comment by haroldmodesto** [comment]
Any news? Thanks for your work on this guys.

**Comment by almogdesign** [comment]
Any news on this?

**Comment by nate-strauser** [comment]
v4.0 published - let me know if you find any issues - thanks!
